[package]
name = "wario"
description = "WebAssembly Rust Interpreter"
version = "0.1.0"
authors = ["Erik Valkering <erikvalkering@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
